### ISSUE TITLE
Meta-model generation to use @KeyType for identifying entity key type

### ISSUE THREAD

**Issue by 01es** [fieldenms/tg#1877]
### Description

At the moment `key` type information is determined from a `key` field declaration, the same way as for all other properties. However, `key` has a special purpose and its type if provided as a type parameter when declaring entities. In those cases where `key` is redeclared, its type is captured correctly for the purpose of meta-model generation. But in all other cases such type would not be determined correctly.

In order to address this shortcoming, it is necessary to use the type information provided as a value for argument `value` of annotation `@KeyType`, which is always present for correctly defined entities either at a type level for the entity or its super types. 

We can use this issue to start introducing compile-time validation for entities. And so, the following conditions should lead to the annotation processor reporting a compile time error:

- [x] 1. Entity definition is missing `@KeyType` i.e., neither the entity type nor its super types have this annotation declared. Abstract entities should be able have no `@KeyType` annotation present.
- [x] 2. The type of key as defined by `@KeyType` does not match the one specified as the type argument to `AbstractEntity` or related descendants, such as `AbstractPersistentEntity`, etc.
- [x] 3. Child entity declares `@KeyType` that does not match the type at the super type level.
- [x] 4. Entity declares property `key` having a type that does not match the one defined by `@KeyType`. Additionally,  if `NoKey` is specified, then it's forbidden to declare property `key`.

A special care should be taken in cases of `@KeyType(NoKey.class)`, where `key` meta-model does not need to be generated.

### Expected outcome
Improved meta-models with correct key types. Compile-time errors for entities with incorrect or missing `@KeyType`.

### Usage
This issue introduces `VerifyingProcessor`, which at this stage is only responsible for verifying entity key declarations (`KeyTypeVerifier`), but has the potential to be enriched with additional verifiers (refer constructor in `VerifyingProcessor` for more details).

`VerifyingProcessor` has significant implications not only in light of the fact that it verifies entity model definitions, but also for correct execution of `MetaModelProcessor`, preventing invalid situations from being encountered during meta-model generation.

Both these processors should be enabled in `pom.xml` for `*-pojo-bl` modules of TG-based applications (Modern Java only). This can be done as outlined below, with `VerifyingProcessor` being the first `processor` in the list.

```xml
<processors>
    <!-- list of processors to use -->
    <processor>ua.com.fielden.platform.processors.verify.VerifyingProcessor</processor>
    <processor>ua.com.fielden.platform.processors.metamodel.MetaModelProcessor</processor>
</processors>
```
