### ISSUE TITLE
Meta-model generation optimisation: always generate an entity meta-model

### ISSUE THREAD

**Issue by homedirectory** [fieldenms/tg#1983]
### Description
The meta-model generation algorithm is designed to handle modifications to entity sources caused by both incremental and full builds.
While full builds are simple to handle, incremental modifications require a more nuanced algorithm, since they imply propagation of changes to affected Java sources.

In the context of entity meta-models incremental builds are handled in the following way:
1. The initial input entities (i.e., those that were modified) have their meta-models regenerated according to their current definition.
2. Java sources (entities in this case) that are affected by the changes to initial inputs are processed in the same manner.

It is convenient to represent entities and their meta-models as graphs, where entity properties and meta-model fields are arcs (directed edges) to other nodes (entities/meta-models). Entities form an entity graph, and meta-models form a meta-graph.  

The proposed optimisation eliminates the need for step 2. Here is why -- step 1 handles a transition of its input entities between one of the following states:
1. Metamodeled     -> Not metamodeled : existing meta-model is regenerated into an inactive one
2. Metamodeled     -> Metamodeled     : existing meta-model is regenerated to reflect structural changes to the entity
3. Not metamodeled -> Metamodeled     : new meta-model is generated

State 2 involves a simple internal modification and therefore does not require regeneration of adjacent meta-nodes.
States 1 and 3, however, require regeneration of adjacent meta-nodes in order to replace references to the now inactive meta-model with `PropertyMetaModel` -- the inactive part of the meta-graph is removed.

This transition between `PropertyMetaModel` and `EntityMetaModel` required by states 1 and 3 is the target of proposed optimisation. Instead of representing meta-arcs that connect non-metamodeled entities using `PropertyMetaModel`, a stripped (of its edges) `EntityMetaModel` can be used -- one that represents a sink node. This way adjacent meta-nodes don't need to be regenerated, and all 3 transition states only imply changes to the representation of the meta-model itself.

This optimisation requires the following changes to the meta-model processor:
- [ ] 1. Generate meta-models for all entities, but generate stripped versions for non-metamodeled entities.
- [ ] 2. Replace transition from active to inactive meta-model by full to stripped meta-model: a stripped (inactive) meta-model should be generated without "arcs" (declared fields).
- [ ] 3. Don't process affected sources.

The proposed change only affects the internal representation, not the interface.

#### Example
Initial domain state:
```java
@DomainEntity
class Vehicle {
    @IsProperty private Make make;
    @IsProperty private Date manufactureDate;
}

@DomainEntity
class Make {
    @IsProperty private String name;
}
```

Generated meta-models:
```java
class VehicleMetaModel extends EntityMetaModel {
    // meta-node for a metamodeled entity is a subtype of EntityMetaModel, as before
    public MakeMetaModel     make()            { return make.get();      };
    // meta-node for an ordinary property has type PropertyMetaModel, as before
    public PropertyMetaModel manufactureDate() { return manufactureDate; };
    public String toPath();
}

class MakeMetaModel extends EntityMetaModel {
    public PropertyMetaModel name() { return name; };
    public String toPath();
}
```

State 1 transition: `Make` is no longer metamodeled, but `VehicleMetaModel` is not affected!
```java
class VehicleMetaModel extends EntityMetaModel {
    // still MakeMetaModel
    public MakeMetaModel     make()            { return make.get();      };
    public PropertyMetaModel manufactureDate() { return manufactureDate; };
    public String toPath();
}

// is transformed from a sub-graph into a sink node
class MakeMetaModel extends EntityMetaModel {
    // no longer declares methods for traversal of properties
    public String toPath();
}
```

### Expected outcome
Simplified meta-model maintenance, reduced computational cost of meta-model generation.

**Comment by homedirectory** [comment]
It was decided to close this issue for the following reasons:
* The proposed approach does not cover all cases. That is, for some cases processing affected sources is essential to ensure correctness. One example is **meta-model hierarchies**. Since meta-models can extend other meta-models, changes to the parent meta-model affect its inheritors. In particular, deactivation of a parent meta-model leads to inheriting meta-models losing access to inherited methods, which would render them as incorrect because the underlying entity still inherits properties from its parent. Therefore, it would be necessary to regenerate inheriting meta-models to break the hierarchy and make all methods declared instead. In this case the set of affected sources would contain all inheritors of the parent meta-model's underlying entity.
* No low-hanging fruit could be identified that would cover the mentioned case without the need to access affected sources.
