### ISSUE TITLE
Improved handling of error types during annotation processing

### ISSUE THREAD

**Issue by homedirectory** [fieldenms/tg#2097]
### Description
It is possible for annotation processors to receive erroneous program elements as input. The `TypeMirror` API even models erroneous types with the `ErrorType` type.

Current implementations of platform annotation processors treat erroneous program elements as unrecoverable errors, and throw a runtime exception upon encountering an `ErrorType`. This limits the applicability of annotation processors. Also, this issue is a good opportunity to formalise the handling of erroneous elements by individual processors. The following is proposed:
- **Meta-model generator**
    - [x] erroneous entity properties should be ignored and ommited in generated meta-models. Currently, such properties are modelled with `PropertyMetaModel`. 
    - [x] erroneous superclass should cause the meta-model generation to be aborted for that entity and a warning reported informing the user of the inability to generate a meta-model for that entity due to its erroneous definition. Currently, a runtime exception is thrown.
- **Verifier**
    - [x] Upon encountering an `ErrorType`, further verification should be skipped ~~and a warning reported informing the user that the program element could not be verified due to its erroneous definition~~ (requirement retracted due to being impractical to implement).

### Expected outcome
Formalised handling of erroneous program elements by annotation processors in a reliable way that is recoverable from errors.
