### ISSUE TITLE
Upgrade and cleanup of Polymer sources

### ISSUE THREAD

**Issue by 01es** [fieldenms/tg#2329]
### Description

In preparation for the new Web UI foundation, the Polymer source needs to be reviewed.
Some of the Polymer files that have been checked into the repo are not required and should be removed.

Besides the Polymer source all of the dependencies inside `src/main/resources/polymer` folder should be cleaned up by removing unused ones. All dependencies in that folder should be updated to the latest possible versions. Also, `antlr4` and `moment/moment-timezone` dependencies should be updated. All existing lib transformations are to be re-applied, if needed (removed otherwise).

- [x] 7. capture current state of Dependabot / Code Scan alerts and current 4 folders in `polymer` directory to be able to compare later
- [x] 1. return fully to original update dependencies; replicate something that was improved on previous steps if any
- [x] 4. regenerate all changes but commit only those, that was changed for web testing dependencies
- [x] 9. run web tests against newly updated web tests infrastructure; if broken then adjust accordingly
- [x] 6. wait for Dependabot / Code Scan to be performed and analyse the results
- [x] 14. Process, collect, document exact transformations we applied earlier to Polymer, shims and components
- [x] 15. Take Polymer/ShadyCSS/WebComponentsJS-related transformations and apply (if needed)
- [x] 12. EGI is not visible under updated Polymer/ShadyCSS/WebComponentsJS
- [x] 8. if there are little vulnerabilities on top of already scanned in 7., try to resolve (manually?); if many -- create list to be able to mark them specifically in github
- [x] 10. ~~webcomponentsjs (already updated in 4.) /~~ web-animations-js
- [x] 2. explicitly add neon-animation dependency
- [x] 20. Flash out patch version updates first: `iron-autogrow-textarea`, ~~`iron-image`~~ (unchanged), ~~`paper-icon-button`~~ (unchanged), `paper-ripple`, ~~`paper-spinner`~~ (unchanged)
- [x] 22. Flash out patch version updates next (with conflicts): `iron-overlay-behavior` (confilicts with `iron-overlay-manager`)
- [x] 21. Flash out patch version updates next (with conflicts): `iron-location`
- [x] 24. Flash out patch version updates (new explicit and actually changed): `iron-resizable-behavior` -- probably only our transformation needs to be applied, because 3.0.1 version (true)
- [x] 23. Minor version updates (new explicit and actually changed): `iron-a11y-announcer`
- [x] 25. Minor version updates (actually changed): `google-chart`, `app-layout`, `iron-list`, [`paper-badge`, `paper-dropdown-menu`, `paper-menu-button` -- removed completely]
- [x] 3. try to avoid iron-test-helpers loading from github, but use npm instead (or remove completely if actually unused)
- [x] 27. Rationalise `build-polymer.js` by removing unused imports and adding used (to load only those element files, that are actually needed).
- [x] 28. Review again WCT and test framework dependencies and remove all unused.
- [x] 26. Minor version updates (actually changed, conflict): `iron-fit-behavior` (no conflict actually), `paper-input`.
- [x] 16. Take component-related transformations and apply (if needed)
- [x] 11. ~~@polymer/polymer (already updated in 4.) and~~ all other components
- [x] 30. Review transformations to existing beyond-Polymer JS libs and flash out them into new `transform` tasks.
- [x] 29. Review existing beyond-Polymer JS libs and flash out them into new `update / remove` tasks.
- [x] 54. Need to preserve `package.json` (?) files for Polymer-driven tree-shaken dependencies to show actual vulnerabilities for them. This will probably increase Dependabot alerts number; hopefully by a little bit. All other dependencies like `moment`, `GraphiQL`, `Leaflet` etc. must follow the same way. Do as part of 32.-53. [0:00, hopefully be resolved by 5.]
- [x] 5. maybe commit package-lock.json to actually promote exact versions downloaded to github for analysing [3:00]
- [x] 56. Consider `package.json` removal for all (or subset of) libraries not to show false positive dev (or even prod) vulnerabilities. Think on negative impact it may have and on further lib version tracking (package-lock.json?). This may supercede task 17 partially of fully.
- [x] 17. apply marks to the list from 8. (post merge?)
- [x] 47. `require/` - remove; unused [0:45]
- [x] 13. improve tg-polymer-utils uuid generation (post 17. on smaller list of alerts; create separate issue) [1:00]
- [x] 60. planning_and_scheduling/jquery-1.11.1.js process actual usage and remove if unused (used in TG Example only, see 35a in #2350)
- [x] 57. Mark Code Scanning `wct-browser-legacy`-related vulnerabilities as `Used in tests | This alert is not in production code` with `Dismissal Reason: This code is a part of wct-browser-legacy infrastructure, that is used exclusively for web tests and is never deployed.` [1:30].
- [x] 61. Check `.bin` folders and whether they may be accidentally skipped through `.gitignore`.
- [x] 50. Remove bad `<script src='/resources/moment/**/**moment-with-locales.js'></script>` tags from examples. [0:15]
- [x] 49. Update `moment` dependency from 2.24.0 (2019) to 2.30.1 (2023) (`moment-with-locales.js`); + `this => window` transform. [3:00]
- [x] 51. Update `moment-timezone` dependency from 0.5.33 (2021a iana) to 0.5.46 (2024b iana) (`moment-timezone-with-data.min.js`); + `this => window` transform; check Firefox errors (no errors now). [1:00]
- [x] 59. Final interactive testing against different projects, mobile / desktop, dev / depl modes + create PR (+web / java tests). [2:00]
- [x] 18. Ensure load tests performance no less than on `develop` branch and improve if degraded; share findings [2:00]
---------------------------------------------------------------
- [x] a. [#1329 Added various performance tweaks to our code, ShadyCSS's apply-shim and iron-resizable/fit-behaviors.](https://github.com/fieldenms/tg/commit/75e988a98e4beb33d9576da2594c11baf41b0934)
  iron-fit-behavior.js
  iron-resizable-behavior.js
  **apply-shim.js**
- [x] b. [#1331 #1331 Next steps implementing long-living service worker that gradually manages cache of resources.](https://github.com/fieldenms/tg/commit/0da4eca58165b7555ff85ce6b196edf56dfbeb57)
  iron-resizable-behavior.js
  **apply-shim.js**
- [x] c. [#1329 Fixed problem that caused entity master to ignore specified size also fixed entity editor problem that didn't closed search panel on outside click.](https://github.com/fieldenms/tg/commit/8cb177db32a990dfd568a8f5c779f30dc77a000d)
  iron-resizable-behavior.js -- reverted one of "performance tweaks"
- [x] d. [#1329 optimised iron-resizable behavior so that it registers listeners after attached. Removed tooltip behavior from all components except the top ones. Fixed focusing traversal.](https://github.com/fieldenms/tg/commit/f57aef25c53a5c509de3abff4058123b150a44a2)
  iron-resizable-behavior.js -- another performance tweak
- [x] e. [#1329 Remved redundant code.](https://github.com/fieldenms/tg/commit/e3f1f54a0a5c630d0648d95da67c4340337230db)
  iron-fit-behavior.js -- reverted one of "performance tweaks"
  **apply-shim.js** -- reverted one of "performance tweaks"
- [x] f. [#1329 Provided comments to apply-shim file to indicate bottlenecks.](https://github.com/fieldenms/tg/commit/a269663f07d36b508be6d0668ac837407ae9c32d)
  **apply-shim.js**
- [x] g. [#1341 Modified iron location so that location uris won't be encoded or decoded inside iron-location component.](https://github.com/fieldenms/tg/commit/3ba40f9fd81978ec897201a29c1f282f4fc20847)
  iron-location.js -- many changes, but probably updated? needs comparison
- [x] h. [#1341 Updated irom location so that it has nodecode property that turns off decoding when needed otherwise it works the way it was before.](https://github.com/fieldenms/tg/commit/e3a060944940d81a7d9f85ed5172ce0e6461a999)
  iron-location.js -- many changes, but probably updated? needs comparison
  app-location.js
- [x] i. [#1341 Reformated code, minor fixes.](https://github.com/fieldenms/tg/commit/c7f94b933d3441d45e29366b610de64389ff0218)
  iron-location.js
- [x] j. [#936 Adjusted CSS for paper-input-error to shorten long messages.](https://github.com/fieldenms/tg/commit/825671c2b8b26ed49f1ff3a3a01795cab2809323)
  paper-input-error.js
- [x] k. [#1107 Added dynamic action to app-template to be able to open master using just uri](https://github.com/fieldenms/tg/commit/37cbae35e77dee757eaf794abc5e09978ed7b265)
  app-location.js
- [x] l. [#1703 Override all paper-checkboxes behavior not to react on Enter key. Chosen to do that in paper-checkbox element because any other implementation options (e.g. wrapping into other element or imperative change of behaviour) would impact performance.](https://github.com/fieldenms/tg/commit/1ae59e69390bba24ae4e07c903324063760af0a9)
  paper-checkbox.js
- [x] m. [#1854 Removed click action that brings to front delayed action toast. Also enhanced overlay behavior to handle always on top overlayes correctly](https://github.com/fieldenms/tg/commit/30a54908f87b59f577d71b440a7fab32d09e71f7)
- [x] n. [#1854 Adjusted overlay manager to close dialog on mouse down event.](https://github.com/fieldenms/tg/commit/2da30f7ef6dc161244c8f4eaf2d1226bcac036d4)
- [x] o. [#1854 Minor code and doc improvements.](https://github.com/fieldenms/tg/commit/e7f616067c1cbb8b7af88afc0e09744bab56297c)
  iron-overlay-manager.js
- [x] p. [#1451 Fixed memory leak in web-component-tester, that is used for web tests running.](https://github.com/fieldenms/tg/commit/5364165d97a0fd119d5bd7d62ef71e593bc09d52)
  **wct-browser-legacy/browser.js**
- [x] ~~lib-g. [#1274 migrated reflection test. Enhnaced moment library with window property instead of this.](2fa34eb87848146b18c1c479f6662c8e7ca2bf7b)
`moment-with-locales.js` (`this => window`)~~
- [x] ~~lib-h. [#1676 Updated moment-timezone-with-data from version 0.5.25 to 0.5.33-2021a. Replaced first 'this' with 'window'.](35de51c11e4982fb62684bbf1b79bfe230a34f64)
`moment-timezone-with-data.js` (`this => window`)~~

### Expected outcome
Removal of unused Polymer files (at least some of them if not all). Update all prod / test dependencies in `src/main/resources/polymer` folder and some additional ones (`antlr4` and `moment/moment-timezone`).

**Comment by jhou-pro** [comment]
Current state of the `polymer` directory tree is the following:
```
.../tg/platform-web-ui/src/main/resources/polymer$ tree -d -L 2
.
├── @google-web-components
│   └── google-chart
├── @polymer
│   ├── app-layout
│   ├── app-route
│   ├── font-roboto
│   ├── iron-a11y-announcer
│   ├── iron-a11y-keys-behavior
│   ├── iron-ajax
│   ├── iron-autogrow-textarea
│   ├── iron-behaviors
│   ├── iron-checked-element-behavior
│   ├── iron-collapse
│   ├── iron-dropdown
│   ├── iron-fit-behavior
│   ├── iron-flex-layout
│   ├── iron-form
│   ├── iron-form-element-behavior
│   ├── iron-icon
│   ├── iron-icons
│   ├── iron-iconset
│   ├── iron-iconset-svg
│   ├── iron-image
│   ├── iron-input
│   ├── iron-jsonp-library
│   ├── iron-list
│   ├── iron-location
│   ├── iron-media-query
│   ├── iron-menu-behavior
│   ├── iron-meta
│   ├── iron-overlay-behavior
│   ├── iron-pages
│   ├── iron-range-behavior
│   ├── iron-resizable-behavior
│   ├── iron-scroll-target-behavior
│   ├── iron-scroll-threshold
│   ├── iron-selector
│   ├── iron-swipeable-container
│   ├── iron-validatable-behavior
│   ├── neon-animation
│   ├── paper-badge
│   ├── paper-behaviors
│   ├── paper-button
│   ├── paper-card
│   ├── paper-checkbox
│   ├── paper-dialog
│   ├── paper-dialog-behavior
│   ├── paper-dialog-scrollable
│   ├── paper-dropdown-menu
│   ├── paper-fab
│   ├── paper-icon-button
│   ├── paper-input
│   ├── paper-item
│   ├── paper-listbox
│   ├── paper-menu-button
│   ├── paper-progress
│   ├── paper-radio-button
│   ├── paper-ripple
│   ├── paper-spinner
│   ├── paper-styles
│   ├── paper-swatch-picker
│   ├── paper-tabs
│   ├── paper-toast
│   ├── paper-toolbar
│   ├── paper-tooltip
│   └── polymer
├── web-animations-js
│   └── src
└── @webcomponents
    ├── shadycss
    └── webcomponentsjs

71 directories
```
This state corresponds to old not updated dependencies without the following ones:
```
--------------------------------------------------------------
PRESENT:
@webcomponents/webcomponentsjs
web-animations-js

@polymer/polymer

@polymer/app-layout
@polymer/app-route
@polymer/iron-*
@polymer/paper-*
@google-web-components/google-chart
@polymer/neon-animation

--------------------------------------------------------------
REMOVED:
@polymer/test-fixture
chai
mocha
wct-browser-legacy
wct-mocha
@polymer/iron-test-helpers (github)

       + from polymer.json extras:
@polymer/sinonjs
```

**Comment by jhou-pro** [comment]
Overview of current state of:

**Dependabot:**
1 Critical, 3 High and 3 Moderate dependencies. All are DEVELOPMENT dependencies.
a) webcomponentsjs (1 High)
b) web-animations-js (1 Critical, 2 High and 3 Moderate)
Try to update dependencies to the newest versions? Or dismiss DEVELOPMENT vulnerabilities?

![image](https://github.com/user-attachments/assets/ab3aa118-fc96-48a0-8e45-8fa2532d56c7)

**Code scanning:**
1. process the need of require js and remove if not needed (Code Scanning 2 Critical and 4 High and 3 Medium alerts -- 9 alerts total)
2. webcomponentsjs -- try to update to resolve 2 Shady CSS style-transformer.js High Code Scanning alerts
3. moment-with-locales -- try to update to resolve 1 High Code Scanning alert
4. esri-leaflet-debug -- remove, because currently not used (2 High Code Scanning alerts)
5. Insecure randomness -- already resolved, needs revulcanisation of TG Example app
6. planning_and_scheduling/jquery-1.11.1.js -- remove if not used, or replace logic by something else (2 Medium Code Scanning alerts)
7. yandex_traffic.html - remove (2 Medium Code Scanning alerts)
8. marker-cluster example -- update http to https (1 Medium Code Scanning alert)

![Selection_999(192)](https://github.com/user-attachments/assets/3c873b9e-3451-4eea-877f-3811afe80e77)
![Selection_999(193)](https://github.com/user-attachments/assets/ae378056-859e-4548-8d3a-75ca4e38b717)
![Selection_999(194)](https://github.com/user-attachments/assets/5dad5a21-ea87-45d2-b987-ad4f1a5ef4da)

**Comment by jhou-pro** [comment]
|lib|old version|new version|
|---|---|---|
|Polymer  |        3.2.0  | 3.5.2|
|ShadyCSS |        1.9.1  | 1.11.2|
|WebComponentsJS |  2.2.10 | 2.8.0|
