### ISSUE TITLE
Upgrade and cleanup of Web UI libraries

### ISSUE THREAD

**Issue by jhou-pro** [fieldenms/tg#2350]
### Description

As a continuation of #2329 and in preparation for the new Web UI foundation, libraries outside `src/main/resources/polymer` folder needs to be reviewed, updated and cleaned up.

- [ ] 34. Move `*-lib.js` wrapper files to separate folder for easier tracking (probably); consider VCS history tracking i.e. do proper refactoring, not as in 2019 during Polymer 3 update. [1:30]
- [ ] 52. Update `eventsource` polyfill from 0.1.6 (2015) to 2.0.2 (2022) (`eventsource.min.js`); consider full removal because all browsers have support since 2020 (no IE11); actually `eventsource.min.js` was not in ServiceWorker and probably didn't work either. [0:45]
- [ ] 49. Update `moment` dependency from 2.23.0 (2018) to 2.30.1 (2023) (`moment-with-locales.js`); + `this => window` transform. [3:00]
- [ ] 51. Update `moment-timezone` dependency from 0.5.33-2021a (2021) to 0.5.46 (2024) (`moment-timezone-with-data.min.js`); + `this => window` transform; check Firefox errors. [1:00]
- [ ] 48. Already updated (?) `zxcvbn` 4.4.2 (2017) (`zxcvbn.js`); (`zxcvbn-lib.html` unused); seemingly no transformations, but be careful [0:45]
- [ ] 46. `Postal` / `Lodash`: remove manual dependencies; insert into `package.json` (4.17.15 (2019) => 4.17.21 (2021), 2.0.5 (2016) =>2.0.6 (2021)) and, possibly, polymer project building; retest pub/sub; try WCT web tests and, if broken, add transformations to `browser.js` (3.10.1 => 4.17.21 incompatible?); `postal.lodash.min.js postal.js postal/1.0.1/postal.min.js lodash.js` -- unused; + `this => window` transform (`../postal/2.0.5/postal.min.js` only). [6:00, if `browser.js` transformations needed]
- [ ] 45. Update `GraphiQL` from `3.2.3` (2024) to `3.7.0` (2024) (remove source maps transformation); Already updated (?) `react[-dom]` 18.3.1 (2024) [2:00]
- [ ] 44. Update `Leaflet` dependency from 1.8.0 (2022) to 1.9.4 (2024); + many transformations [6:00]
- [ ] 43. other Leaflet plugins... scope unknown... [6:00]
- [ ] 42. Update `Leaflet.Editable` dependency from 1.2.0 (2018) to 1.3.0 (2024) (`Leaflet.Editable.js`) ESRI integration only [1:00]
- [ ] 41. Update `Leaflet.easybutton.fontawesome` dependency from `4.6.3` (2016) to `4.7.0` (2016) or to `6.6.0` (2024) (`../easybutton/fontawesome/..`); + check probably squashed `/resources/..` transform; or remove this dependency completely, because used only in one `fitToBounds` button (`fa-compress`). [2:00]
- [ ] 40. Already updated (?) `Leaflet.easybutton` 2.4.0 (2019) (`easy-button[.css].js`) [0:45]
- [ ] 39. Already updated (?) `Leaflet.draw` 1.0.4 (2018) (`leaflet.draw.css.js leaflet.draw-src.js`) + mark many transformations. [1:30]
- [ ] 38. Already updated (?) `Leaflet.loading` 0.1.24 (2017) (`Control.Loading[.css].js`) + mark `base64` transform. [0:45]
- [ ] 37. Update `fullcalendar` dependency from 5.6.0 (2020) to 6.1.15 (2024) (`main.js, main.css -> fullcalendar-style.js`; `locales-all.js` unused) [2:00]
- [ ] 36. Update `FileSaver` dependency from 1.1.20160328 (2016) to 2.0.5 (2020) (`FileSaver[.min].js`). [2:00]
- [ ] 35. Update `d3` dependency from 4.4.1 (2017) to 7.9.0 (2024) (`d3[.min].js`); + `this => window` transform. [4:00, with OM?]
- [ ] 50. Remove bad `<script src='/resources/moment/**/**moment-with-locales.js'></script>` tags from examples. [0:15]
- [ ] 33. Move `bus/spike` and similar to `spikes` for a cleaner, more structured code base. [0:15]
- [ ] 32. Remove unused `entity.js` and similar old files. [0:30]
- [ ] approx total [42:00]
---------------------------------------------------------------
- [ ] 58. Process `install-polymer.sh` script log on warnings; try to resolve them, perhaps by overriding some dependencies.
- [ ] 58a. npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
- [ ] 58b. npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
- [ ] 58c. (node:840797) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
- [ ] 58d. (node:840797) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
- [ ] 53. Consider removal of other polyfills relative to existing browser support (some real checks still need to be done); the lesser polyfills the better (according to the need to maintain them and vulnerability risks).
- [ ] 19. fix web test running percentages (shows above 100%) for enhanced WCT browser.js (see task 9.) in combination with newer major versions of Chai / Mocha; review `browser.js` transformations related to Mocha again after new update.
- [ ] 55. move test-fixture out of polymer building process (no tree shaking), which would complete move of testing framework to be managed exclusively by npm
- [ ] 31. Create wiki with all HTML / JS / CSS lib transformations
---------------------------------------------------------------
- [ ] lib-a. [#1268 Migrated d3 bar chart and tg bar chart and it's example.](https://github.com/fieldenms/tg/commit/0dcdfbbd6833892cb3e409214fbae5818cb249cc)
d3.js (`this => window`)
d3.min.js (`this => window`)
- [ ] lib-b. [#1713 34. Replaced the use of base64 gifs in Leaflet / Leaflet Control Loading by usage of internally downloaded gifs. Added them to vulcanising utility.](https://github.com/fieldenms/tg/commit/699349534ea4ca145d53d772bf5e3da8b75cf1fd)
Control.Loading.css.js
leaflet-src.js
- [ ] lib-c. [#1271 Temporal fix for leaflet's (+plugins') images until better solution will be provided.](https://github.com/fieldenms/tg/commit/94936cf34d2ea27b24f316959df365ad362210ca)
[#1271 Completed migration to new version of leaflet and plugins (control-loading, draw, easybutton, markercluster).](https://github.com/fieldenms/tg/commit/306c456a8ad7c14d20a6453f9196438b7215e4db)
leaflet.draw.css.js
780f18dc91f52899e8b4cfa982c2eb99036f4598 cac811789cb059945188231d45d3933d4b751545 09328ed01ffd57a99c4411a9b60d3c86ea20b1d2 9b21df194720c442440a65257356b99df803a8c7 3efaa25c2db471944a43a3df821cfb302ffb4780 e67034c278dc32974930feab7b2c9ebfeb53fca7 bfabe9018e774a34f803b958fc901a8d41854ad7 de16c1768ba275e924f7efcb8cbdcfea326186c9
leaflet.draw-src.js
- [ ] lib-d. 07910257458306c72aa3a6f35a5a5959296875a8 53004f179e547c213370d6b3b956f856f8c67663
font-awesome.css.js
- [ ] lib-e. 94936cf34d2ea27b24f316959df365ad362210ca 306c456a8ad7c14d20a6453f9196438b7215e4db cec2f6a3870b3855d597cc870d98c3184dbcc86b 276ac6bea4a67d3b3b96702166f170b08ee193cd 699349534ea4ca145d53d772bf5e3da8b75cf1fd 99d2a324132f70c599a19f8c76307110bf102ce1 a989c1b4ecf5126ef9abd477e7515bf266fc6037 a9f18c3cc1f591eaad4d614a0a07b38bf4cc9194
leaflet-src.js
leaflet.css.js
- [ ] lib-f. a97bb02d0849db97b1d0e005fa71708f45709ab0
`postal.min.js` (`this => window`)
- [ ] lib-g. 2fa34eb87848146b18c1c479f6662c8e7ca2bf7b
`moment-with-locales.min.js` (`this => window`)
- [ ] lib-h. 35de51c11e4982fb62684bbf1b79bfe230a34f64
`moment-timezone-with-data.min.js` (`this => window`)

### Expected outcome

Clean and up-to-date Web UI library dependencies without security issues.
